[package]
name = "htl3r-da"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Julian Burger <https://github.com/cauvmou>"]
license = "0BSD"
description = "HTL-Rennweg diploma thesis template."
homepage = "https://www.htlrennweg.at"
keywords = ["Diplomarbeit", "thesis", "diploma", "HTL Rennweg", "htl3r", "wien"]
categories = ["thesis"]

[template]
path = "template"
entrypoint = "main.typ"
