[package]
name = "htl3r-da"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = [
    "Julian Burger <https://github.com/cauvmou>",
    "Viktor Kreuzer <https://github.com/kre9>",
    "David Koch <https://github.com/Davideko212>",
    "Bernd Reither <https://github.com/sidious38>",
]
license = "0BSD"
description = "HTL-Rennweg diploma thesis template."
homepage = "https://www.htlrennweg.at"
keywords = ["Diplomarbeit", "thesis", "diploma", "HTL Rennweg", "htl3r", "wien"]
categories = ["thesis"]
compiler = "0.12.0"
exclude = [
  ".git",
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile"
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"

[tool.typst-test]
vcs = "git"
